parameters:
#    sitebolg.example.class: Site\bolgBundle\Example

services:
#    sitebolg.example:
#        class: %sitebolg.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
